function precip_AppendPrecipitationAreaTimeseries(csvFile, timestep, timeSeconds, metrics)
% precip_AppendPrecipitationAreaTimeseries - Append one precipitation-area row.

requiredFields = { ...
    'totalNetSolidArea_cm2', ...
    'firstPoreNetSolidArea_cm2', ...
    'firstThreePoresNetSolidArea_cm2', ...
    'totalSolidArea_cm2', ...
    'firstPoreSolidArea_cm2', ...
    'firstThreePoresSolidArea_cm2'};
for iField = 1:numel(requiredFields)
    fieldName = requiredFields{iField};
    if ~isstruct(metrics) || ~isfield(metrics, fieldName) || ...
            ~isnumeric(metrics.(fieldName)) || ~isscalar(metrics.(fieldName)) || ...
            ~isfinite(metrics.(fieldName))
        error('RTSPHEM:Precipitate:InvalidAreaTimeseriesMetrics', ...
            'Metric %s must be a finite numeric scalar.', fieldName);
    end
end
if ~isnumeric(timestep) || ~isscalar(timestep) || ~isfinite(timestep) || ...
        timestep < 0 || abs(timestep - round(timestep)) > 0
    error('RTSPHEM:Precipitate:InvalidAreaTimeseriesStep', ...
        'Timestep must be a finite nonnegative integer scalar.');
end
if ~isnumeric(timeSeconds) || ~isscalar(timeSeconds) || ~isfinite(timeSeconds)
    error('RTSPHEM:Precipitate:InvalidAreaTimeseriesTime', ...
        'Time must be a finite numeric scalar.');
end

fid = fopen(csvFile, 'a');
if fid == -1
    error('RTSPHEM:Precipitate:AreaTimeseriesOpenFailed', ...
        'Cannot append precipitation area time-series CSV: %s', csvFile);
end
cleanupObj = onCleanup(@() fclose(fid));
fprintf(fid, '%d,%.12g,%.12e,%.12e,%.12e,%.12e,%.12e,%.12e\n', ...
    timestep, timeSeconds, ...
    metrics.totalNetSolidArea_cm2, ...
    metrics.firstPoreNetSolidArea_cm2, ...
    metrics.firstThreePoresNetSolidArea_cm2, ...
    metrics.totalSolidArea_cm2, ...
    metrics.firstPoreSolidArea_cm2, ...
    metrics.firstThreePoresSolidArea_cm2);
clear cleanupObj;
end
