function tests = test_PNMPhreeqcSessionConfig
tests = functiontests(localfunctions);
end

function testPersistentSessionIsConfiguredOnlyForPhreeqcPath(testCase)
rtmDir = fileparts(fileparts(mfilename('fullpath')));
pnmPath = fullfile(rtmDir, 'PNM_beauty3.m');
text = string(fileread(pnmPath));

verifyTrue(testCase, contains(text, ...
    "phreeqcPersistSession = logical(cfgget(config, 'phreeqcPersistSession', true));"), ...
    'PNM_beauty3 should expose a default-on persistent PHREEQC session flag.');
verifyTrue(testCase, contains(text, ...
    "if usePhreeqc && phreeqcPersistSession"), ...
    'Persistent PHREEQC session creation must be guarded by usePhreeqc.');
verifyTrue(testCase, contains(text, ...
    "rtm.phreeqc.PhreeqcSession"), ...
    'PNM_beauty3 should create the package PHREEQC session wrapper.');
verifyTrue(testCase, contains(text, ...
    "'phreeqcSession', phreeqcSession"), ...
    'RunPhreeqcCalciteBatch options should receive the persistent session.');
verifyTrue(testCase, contains(text, ...
    "'writeInputFiles', ~phreeqcUseRunString"), ...
    'RunString mode should avoid per-step PHREEQC input files by default.');
verifyTrue(testCase, contains(text, ...
    "phreeqcSessionCleanup = onCleanup(@() phreeqcSession.close());"), ...
    'The persistent PHREEQC session should be closed automatically.');
end

function testPhreeqcGeometryUsesSharedCutCellMetrics(testCase)
rtmDir = fileparts(fileparts(mfilename('fullpath')));
pnmPath = fullfile(rtmDir, 'PNM_beauty3.m');
text = string(fileread(pnmPath));

verifyTrue(testCase, contains(text, ...
    "rtm.geometry.BuildCutCellMetrics(grid, levels,"), ...
    'PNM_beauty3 PHREEQC geometry should use the shared cut-cell metric builder.');
end

function testAdaptiveTimeGridExtendsAllPhreeqcSpecies(testCase)
rtmDir = fileparts(fileparts(mfilename('fullpath')));
pnmPath = fullfile(rtmDir, 'PNM_beauty3.m');
text = string(fileread(pnmPath));

verifyTrue(testCase, contains(text, ...
    "transportProblemsToExtend = {hydrogenTransport; calciumTransport;"), ...
    'Adaptive time-grid growth must extend every PHREEQC transport variable.');
verifyTrue(testCase, contains(text, ...
    "carbonTransport; sodiumTransport; chlorideTransport};"), ...
    'Adaptive time-grid growth must include carbonate and electrolyte species.');
verifyTrue(testCase, contains(text, ...
    "extendTransportVariablesToStepper(transportProblemsToExtend{iTransportExtend});"), ...
    'Every selected transport problem must be extended after appending a time step.');
end
